config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get '/sitemap.xml', to: redirect('/sitemap.xml.gz')

  root to: "pages#index"
  get "contact", to: "pages#contact", as: "contact"
  post "contact", to: "contacts#create"
  post "locations", to: "locations#find_nearby"

  resources :venues, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="w-3/4 bg-saffron-mango-100 border border-saffron-mango-400 text-saffron-mango-700 px-4 py-3 rounded absolute top-5 right-5" role="alert" data-controller="flash" data-flash-target="flashDiv">
    <button type="button" class="absolute top-0 bottom-0 right-0 px-4 py-3" data-bs-dismiss="alert" aria-label="Close" data-action="click->flash#close">
      <svg class="fill-current h-6 w-6 text-saffron-mango-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="w-3/4 bg-saffron-mango-100 border border-saffron-mango-400 text-saffron-mango-700 px-4 py-3 rounded absolute top-5 right-5" role="alert" data-controller="flash" data-flash-target="flashDiv">
    <button type="button" class="absolute top-0 bottom-0 right-0 px-4 py-3" data-bs-dismiss="alert" aria-label="Close" data-action="click->flash#close">
      <svg class="fill-current h-6 w-6 text-saffron-mango-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div data-controller="dropdown" class="relative flex justify-between w-full lg:h-screen lg:min-w-20 lg:max-w-20 shadow-[0_5px_5px_rgba(0,0,0,0.1)] py-1 md:py-2 lg:py-6 z-50">
  <div class="flex lg:flex-col justify-between lg:justify-start items-center w-full mx-2 lg:mx-4">
    <%= link_to root_path do %>
      <div class="flex items-center lg:flex-col lg:justify-between relative group">
        <%= image_tag "parma.png", alt: "Parmageddon logo small", class: "lg:block mr-2 md:mr-4 lg:mr-0 w-[45px] md:w-[60px]" %>
        <span class="absolute top-full left-1/4 lg:left-1/2 transform -translate-x-1/2 mt-2 px-2 py-1 bg-saffron-mango-700 text-saffron-mango-50 text-sm rounded opacity-0 transition-opacity duration-300 group-hover:opacity-100">
          Parma Home
        </span>
        <h1 class="lg:hidden text-base md:text-2xl font-semibold text-saffron-mango-900">PARMAGEDDON</h1>
      </div>
    <% end %>
    <div class="hidden lg:h-3/4 lg:flex lg:flex-col lg:justify-between lg:mt-auto lg:mb-6">
      <%= link_to root_path, class: "relative group" do %>
        <%= image_tag "home-icon.svg", alt: "Home icon", class: "mr-2 md:mr-4 lg:mr-0 w-[45px] md:w-[60px]" %>
        <span class="absolute top-full left-1/2 transform -translate-x-1/2 mt-2 px-2 py-1 bg-saffron-mango-700 text-saffron-mango-50 text-sm rounded opacity-0 transition-opacity duration-300 group-hover:opacity-100">
          Home
        </span>
      <% end %>
      <%= link_to venues_path, class: "relative group" do %>
        <%= image_tag "venues-icon.svg", alt: "Venues icon", class: "mr-2 md:mr-4 lg:mr-0 w-[45px] md:w-[60px]" %>
        <span class="absolute top-full left-1/2 transform -translate-x-1/2 mt-2 px-2 py-1 bg-saffron-mango-700 text-saffron-mango-50 text-sm rounded opacity-0 transition-opacity duration-300 group-hover:opacity-100">
          Venues
        </span>
      <% end %>
      <%= link_to contact_path, class: "relative group" do %>
        <%= image_tag "contact-icon.svg", alt: "Contact icon", class: "mr-2 md:mr-4 lg:mr-0 w-[45px] md:w-[60px]" %>
        <span class="absolute top-full left-1/2 transform -translate-x-1/2 mt-2 px-2 py-1 bg-saffron-mango-700 text-saffron-mango-50 text-sm rounded opacity-0 transition-opacity duration-300 group-hover:opacity-100">
          Contact
        </span>
      <% end %>
      <div class="flex flex-col justify-between items-center">
        <%= link_to "https://www.facebook.com/people/Parmageddon/61567884756926/" do %>
          <%= image_tag "facebook-logo.png", size: "30x30" %>
        <% end %>
        <%= link_to "https://www.instagram.com/parmageddonnet/" do %>
          <%= image_tag "instagram-logo.png", size: "30x30", class: "my-4" %>
        <% end %>
        <%= link_to "https://www.linkedin.com/company/104994736/" do %>
          <%= image_tag "linkedin-logo.png", size: "30x30" %>
        <% end %>
      </div>
    </div>
    <%= button_tag type: "button", class: "relative lg:hidden w-[40px] md:w-[60px] h-[40px] md:h-[60px] z-50 flex items-center justify-center", data: { action: "click->dropdown#toggleMenu" } do %>
      <%= image_tag "menu-icon.svg", alt: "Open menu icon", data: { "dropdown_target": "lines" }, class: "absolute w-[40px] md:w-[60px] h-[40px] md:h-[60px] transition-opacity transform duration-300 ease-in-out opacity-100" %>
      <%= image_tag "menu-close.svg", alt: "Close menu icon", data: { "dropdown_target": "cross" }, class: "absolute w-[40px] md:w-[60px] h-[40px] md:h-[60px] transition-opacity transform duration-300 ease-in-out opacity-0" %>
    <% end %>
  </div>
  <div data-dropdown-target="menu" class="hidden flex-col items-center absolute top-10 md:top-20 left-0 right-0 transition ease-in-out duration-500 bg-saffron-mango-20 border-y-2 border-saffron-mango-700 font-semibold text-xl md:text-2xl text-saffron-mango-950 py-2">
    <%= link_to root_path, class: "w-full" do %>
      <div class="transition ease-in-out duration-300 hover:bg-saffron-mango-500 h-full text-center hover:text-saffron-mango-200 py-2 md:py-4">
        <h2>Home</h2>
      </div>
    <% end %>
    <%= link_to venues_path, class: "w-full" do %>
      <div class="transition ease-in-out duration-300 hover:bg-saffron-mango-500 h-full text-center hover:text-saffron-mango-200 py-2 md:py-4">
        <h2>Venues / Ratings</h2>
      </div>
    <% end %>
    <%= link_to contact_path, class: "w-full" do %>
      <div class="transition ease-in-out duration-300 hover:bg-saffron-mango-500 h-full text-center hover:text-saffron-mango-200 py-2 md:py-4">
        <h2>Contact</h2>
      </div>
    <% end %>
    <div class="flex justify-center items-center py-2 md:py-4 h-10 md:h-14">
      <%= link_to "https://www.facebook.com/people/Parmageddon/61567884756926/" do %>
        <%= image_tag "facebook-logo.png", size: "30x30", class: "hover:w-10 hover:h-10" %>
      <% end %>
      <%= link_to "https://www.instagram.com/parmageddonnet/" do %>
        <%= image_tag "instagram-logo.png", size: "30x30", class: "hover:w-10 hover:h-10 mx-4 md:mx-6" %>
      <% end %>
      <%= link_to "https://www.facebook.com/people/Parmageddon/61567884756926/" do %>
        <%= image_tag "linkedin-logo.png", size: "30x30", class: "hover:w-10 hover:h-10" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_map.html.erb
<%= button_tag "Search here", class: "transition ease-in-out duration-300 bg-saffron-mango-300 text-saffron-mango-700 hover:bg-saffron-mango-500 font-semibold hover:text-saffron-mango-100 py-1 md:py-2 px-1.5 md:px-3 mr-1 md:mr-4 border border-saffron-mango-600 focus:border-saffron-mango-800 hover:border-transparent rounded z-50 absolute top-2 left-2", data: { action: "click->google-maps#centerMap" } %>
<div id="page-loader" data-google-maps-target="loaderDiv" class="loader absolute inset-0 flex items-center justify-center z-50">
  <div class="w-12 h-12 border-4 border-t-4 border-t-blue-500 border-gray-300 rounded-full animate-spin"></div>
</div>
<div id="map" class="flex justify-center items-center w-full h-full opacity-50" data-google-maps-target="mapDiv"></div>