config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get '/sitemap.xml', to: redirect('/sitemap.xml.gz')

  root to: "pages#index"
  get "contact", to: "pages#contact", as: "contact"
  post "contact", to: "contacts#create"
  post "locations", to: "locations#find_nearby"

  resources :venues, only: [:index, :show] do
    resources :ratings, only: [:new, :create]
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  has_many :ratings, dependent: :destroy

  validates :name, :suburb, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def update_rating_averages
    self.total_rating_average = ratings.average(:total_rating)
    self.chicken_rating_average = ratings.average(:chicken_rating)
    self.crumb_rating_average = ratings.average(:crumb_rating)
    self.topping_rating_average = ratings.average(:topping_rating)
    self.sides_rating_average = ratings.average(:sides_rating)
    self.venue_rating_average = ratings.average(:venue_rating)
    self.price_average = ratings.average(:price)
    save
  end

  def slug_candidates
    [
      ["#{name} #{suburb}"],
      ["#{name} #{suburb} #{id}"]
    ]
  end
end

app/controllers/venues_controller.rb
require "cgi"

class VenuesController < ApplicationController
  before_action :set_venue, only: [:show]

  def index
    if params[:select] == "venue"
      @venues = Venue.where("name ILIKE ?", "%#{params[:venue]}%")
    elsif params[:select] == "location"
      @venues = Venue.where("suburb ILIKE :location OR postcode ILIKE :location", location: "%#{params[:location]}%")
    else
      @venues = Venue.all
    end
  end

  def show
    @rating = Rating.new
  end

  private

  def set_venue
    # puts "Received params[:id]: #{params[:id]}"
    @venue = Venue.friendly.find(params[:id])
  end
end

app/views/venues/_details.html.erb
<div class="flex-col flex-grow h-full text-saffron-mango-900 px-2" data-venue-details-target="detailsDiv">
  <div class="flex flex-col items-end h-full mt-3">
    <p><%= venue.address %></p>
    <p><%= venue.phone %></p>
    <%= link_to "#{venue.website}", venue.website, class: "transition ease-in-out duration-300 text-saffron-mango-800 hover:text-saffron-mango-950" %>
    <h4 class="mt-3 text-xs">Opening hours</h4>
    <% if venue.hours %>
      <% JSON.parse(venue.hours).each do |hours| %>
        <p class="text-xs"><%= hours %></p>
      <% end %>
    <% else %>
      <p>Not provided</p>
    <% end %>
  </div>
</div>

app/views/venues/_ratings.html.erb
<div class="flex flex-col h-full" data-venue-details-target="ratingsDiv">
  <ul class="flex flex-col items-end text-xl py-1 pr-3">
    <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 pb-2">
      <p class="font-bold">MEAT</p>
      <span class="material-symbols-sharp !font-bold !text-2xl ml-2 mr-5">
        star
      </span>
      <p><%= venue.chicken_rating_average %></p>
    </li>
    <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 py-1.5">
      <p class="font-bold">CRUMB</p>
      <span class="material-symbols-sharp !font-bold !text-2xl ml-2 mr-5">
        star
      </span>
      <p><%= venue.crumb_rating_average %></p>
    </li>
    <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 py-1.5">
      <p class="font-bold">TOPPING</p>
      <span class="material-symbols-sharp !font-bold !text-2xl ml-2 mr-5">
        star
      </span>
      <p><%= venue.topping_rating_average %></p>
    </li>
    <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 py-1.5">
      <p class="font-bold">SIDES</p>
      <span class="material-symbols-sharp !font-bold !text-2xl ml-2 mr-5">
        star
      </span>
      <p><%= venue.sides_rating_average %></p>
    </li>
    <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 py-1.5">
      <p class="font-bold">VENUE</p>
      <span class="material-symbols-sharp !font-bold !text-2xl ml-2 mr-5">
        star
      </span>
      <%= venue.venue_rating_average %></p>
    </li>
    <li class="flex justify-end items-center w-48 pt-2">
      <p class="font-bold mr-6">PRICE</p>
      <p>$<%= number_with_precision venue.price_average.round(1), :precision => 2 %></p>
    </li>
  </ul>
  <div class="flex justify-between items-center text-xl border-y border-saffron-mango-950 mt-auto px-4 py-1.5">
    <div class="flex justify-between items-center">
      <p>
        <p class="font-bold">TOTAL</p>
        <span class="material-symbols-sharp !font-bold !text-2xl ml-2 mr-5">
          star
        </span>
        <p><%= venue.total_rating_average %></p>
      </p>
    </div>
    <div>
      <p>Rated <%= venue.ratings.count %> times</p>
    </div>
  </div>
</div>

app/views/venues/index.html.erb
<%
  set_meta_tags(
    title: "Venues | Venue list.. search all venues or search by venue name or location",
    description: "List of all venues added to Parmageddon.net. Search by venue name or location. Sort results by any type.",
    keywords: "Parma, Venue, Rate, Search"
  )
%>
<div class="lg:w-full lg:flex lg:flex-col lg:box-border" data-controller="fetch-nearby-venues" data-fetch-nearby-venues-apikey-value=<%= ENV.fetch('GMAPS_GEO_API_KEY') %>>
  <div data-fetch-nearby-venues-target="spinner" style="display: none;" class="loader absolute inset-0 flex items-center justify-center z-50">
    <div class="w-12 h-12 border-4 border-t-4 border-t-blue-500 border-gray-300 rounded-full animate-spin"></div>
  </div>
  <div data-fetch-nearby-venues-target="mainDiv">
    <div class="lg:w-full flex flex-col justify-between items-center py-2 mb-2 bg-saffron-mango-50" data-controller="toggle-index-search">
      <h1 class="text-base md:text-2xl font-['Open_Sans'] font-semibold text-saffron-mango-900 mb-4">Venues + Ratings</h1>
      <h2 class="font-bold text-saffron-mango-900">Search by:</h2>
      <div class="flex justify-center items-center my-1">
        <%= form_with url: venues_path, method: :get, local: true, data: { action: "submit->fetch-nearby-venues#search" } do |form| %>
          <div class="flex justify-center items-center my-1">
            <%= form.radio_button :select, "venue", checked: true, class: "w-4 h-4 text-saffron-mango-600 bg-saffron-mango-100 border-saffron-mango-400 focus:ring-saffron-mango-500 focus:ring-2 mx-2",
              data: { action: "click->toggle-index-search#showVenue" } %>
            <%= form.label :select_venue, "Venue", class: "mr-2" %>
            <%= form.radio_button :select, "location", class: "w-4 h-4 text-saffron-mango-600 bg-saffron-mango-100 border-saffron-mango-400 focus:ring-saffron-mango-500 focus:ring-2 mx-2",
              data: { action: "click->toggle-index-search#showLocation" } %>
            <%= form.label :select_location, "Location" %>
            <%= form.radio_button :select, "all", class: "w-4 h-4 text-saffron-mango-600 bg-saffron-mango-100 border-saffron-mango-400 focus:ring-saffron-mango-500 focus:ring-2 mx-2",
              data: { action: "click->toggle-index-search#showAll", fetch_nearby_venues_target: "allInput" } %>
            <%= form.label :select_all, "Show all" %>
          </div>
          <div class="flex justify-center md:w-full">
            <%= form.text_field :venue, placeholder: "Enter venue name", class: "block w-60 lg:w-80 px-2 py-1 text-sm text-center bg-saffron-mango-50 active:bg-saffron-mango-50 border-saffron-mango-300 focus:outline-none focus:ring-saffron-mango-600 focus:border-saffron-mango-800 rounded-md",
            data: { toggle_index_search_target: "venue", fetch_nearby_venues_target: "venueInput" } %>
            <%= form.text_field :location, placeholder: "Enter suburb or postcode, etc", class: "hidden w-60 lg:w-80 px-2 py-1 text-sm text-center bg-saffron-mango-50 active:bg-saffron-mango-50 border-saffron-mango-300 focus:outline-none focus:ring-saffron-mango-600 focus:border-saffron-mango-800 rounded-md",
            data: { toggle_index_search_target: "location", fetch_nearby_venues_target: "locationInput" } %>
            <%= form.submit "GO", class: "transition ease-in-out duration-300 text-white bg-saffron-mango-600 hover:bg-saffron-mango-800 focus:ring-4 focus:ring-saffron-mango-300 font-medium rounded-lg text-xs px-4 py-2 ml-2 focus:outline-none" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="relative shadow-md overflow-x-auto rounded-sm">
      <table class="w-full text-sm text-left text-saffron-mango-600" data-controller="table-sort">
        <thead class="text-xs text-saffron-mango-700 uppercase bg-saffron-mango-50">
          <tr>
            <th scope="col" class="cursor-pointer text-xs text-left px-3 py-1.5" data-action="click->table-sort#sort" data-column="venue"><h4>Venue<span class="ml-2">&#8595;</span></h4></th>
            <th scope="col" class="cursor-pointer text-xs text-left px-3 py-1.5" data-action="click->table-sort#sort" data-column="location"><h4>Location<span class="ml-2">&#8595;</span></h4></th>
            <th scope="col" class="cursor-pointer text-xs text-right px-3 py-1.5" data-action="click->table-sort#sort" data-column="price"><h4>Price<span class="ml-2">&#8595;</span></h4></th>
            <th scope="col" class="cursor-pointer text-xs text-right px-3 py-1.5 lg:pr-12" data-action="click->table-sort#sort" data-column="rating">Rating</h4><span class="ml-2">&#8595;</span></h4></th>
          </tr>
        </thead>
        <tbody data-table-sort-target="tableBody" data-fetch-nearby-venues-target="tableBody">
          <% if @venues.any? %>
            <% @venues.each do |venue| %>
              <tr class="odd:bg-white even:bg-saffron-mango-50 border-b">
                <td scope="row" data-column="venue" class="px-3 py-2 font-medium text-saffron-mango-900 text-xs">
                  <%= link_to venue_path(venue.slug, latitude: venue.latitude, longitude: venue.longitude) do %>
                    <%= venue.name %>
                  <% end %>
                </td>
                <td scope="row" data-column="location" class="px-3 py-2 font-medium text-saffron-mango-900 text-xs"><%= venue.suburb %></td>
                <td scope="row" data-column="price" class="px-3 py-2 font-medium text-saffron-mango-900 text-xs text-right"><%= venue.price_average > 0 ? number_to_currency(venue.price_average) : "-" %></td>
                <td scope="row" data-column="rating" class="px-3 py-2 lg:pr-12 font-medium text-saffron-mango-900 text-xs text-right"><%= venue.total_rating_average %></td>
              </tr>
            <% end %>
          <% else%>
            <tr class="odd:bg-white even:bg-saffron-mango-50 border-b">
              <td colspan="4" class="px-3 py-2 font-medium text-saffron-mango-900 text-xs">No venues match your search.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="flex justify-center my-3">
      <p class="text-xs text-saffron-mango-900"><em>Can't find what you're looking for? Try searching on the <%= link_to "map", root_path, class: "text-saffron-mango-700 underline" %></em></p>
    </div>
  </div>
</div>

app/views/venues/show.html.erb
<%
  set_meta_tags(
    title: "Venue | #{@venue.name}. View ratings, details, search for venues on our map. Submit a parma rating for this venue",
    description: "View all details for this venue. Ratings, address, contact details & website. Search for a venue on our map. Submit a rating for this venue.",
    keywords: "Parma, Venue, Rate, Search, Map"
  )
%>
<div class="flex flex-col flex-grow w-full lg:w-11/12 h-full lg:h-screen" data-controller="venue-details">
  <turbo-frame id="venue-details" data-turbo-action="replace" data-turbo="false" class="flex flex-col lg:flex-row h-full">
    <div class="min-h-[70%] lg:h-full flex flex-col lg:w-full font-['Open_Sans'] text-saffron-mango-900 lg:mx-3" style="background-image: url(<%= image_path "parma-trans.png" %>);background-repeat:no-repeat;background-size:cover 80%;">
      <div class="px-2 md:px-4 py-2 md:py-4 whitespace-nowrap lg:whitespace-normal" data-controller="text-shrink">
        <h1 class="text-2xl sm:text-4xl font-semibold" data-text-shrink-target="text"><%= @venue.name %></h1>
        <div class="w-1/4 md:w-1/3 h-1 py-1 md:py-2.5 ml-2 border-b-2 border-saffron-mango-950"></div>
      </div>
      <div class="flex justify-between mx-4 md:mx-8 lg:my-4">
        <div class="flex flex-col justify-between my-2 md:my-3" data-venue-details-target="buttonsDiv">
          <form>
            <select id="countries" class="custom-select !text-sm md:!text-base lg:!text-lg w-[6rem] md:w-[10rem] transition ease-in-out duration-300 bg-saffron-mango-300 text-saffron-mango-700 hover:bg-saffron-mango-500 font-semibold hover:text-saffron-mango-100 py-1 md:py-2 px-1.5 md:px-3 mr-1 md:mr-4 border border-saffron-mango-600 focus:border-saffron-mango-800 hover:border-transparent rounded", data-action="change->venue-details#handleSelect">
              <option value="ratings" class="!text-sm md:!text-base lg:!text-lg">Ratings</option>
              <option value="details" class="!text-sm md:!text-base lg:!text-lg">Details</option>
            </select>
          </form>
        </div>
        <div data-venue-details-target="ratingsDiv">
          <ul class="flex flex-col items-end text-xl md:text-3xl lg:mt-16">
            <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 pb-2 md:pb-4 lg:pb-4 [@media(max-height:700px)]:pb-1">
              <h3 class="font-bold">MEAT</h3>
              <%= image_tag "google-star-24px.svg", alt: "Rating star", class: "md:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-30px.svg", alt: "Rating star", class: "hidden md:block lg:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-36px.svg", alt: "Rating star", class: "hidden lg:block ml-2 mr-5" %>
              <h3><%= @venue.chicken_rating_average %></h3>
            </li>
            <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 py-1.5 md:py-2 lg:py-4 [@media(max-height:700px)]:py-1">
              <h3 class="font-bold">CRUMB</h3>
              <%= image_tag "google-star-24px.svg", alt: "Rating star", class: "md:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-30px.svg", alt: "Rating star", class: "hidden md:block lg:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-36px.svg", alt: "Rating star", class: "hidden lg:block ml-2 mr-5" %>
              <h3><%= @venue.crumb_rating_average %></h3>
            </li>
            <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 py-1.5 md:py-2 lg:py-4 [@media(max-height:700px)]:py-1">
              <h3 class="font-bold">TOPPING</h3>
              <%= image_tag "google-star-24px.svg", alt: "Rating star", class: "md:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-30px.svg", alt: "Rating star", class: "hidden md:block lg:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-36px.svg", alt: "Rating star", class: "hidden lg:block ml-2 mr-5" %>
              <h3><%= @venue.topping_rating_average %></h3>
            </li>
            <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 py-1.5 md:py-2 lg:py-4 [@media(max-height:700px)]:py-1">
              <h3 class="font-bold">SIDES</h3>
              <%= image_tag "google-star-24px.svg", alt: "Rating star", class: "md:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-30px.svg", alt: "Rating star", class: "hidden md:block lg:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-36px.svg", alt: "Rating star", class: "hidden lg:block ml-2 mr-5" %>
              <h3><%= @venue.sides_rating_average %></h3>
            </li>
            <li class="flex justify-end items-center border-b border-saffron-mango-950 w-48 py-1.5 md:py-2 lg:py-4 [@media(max-height:700px)]:py-1">
              <h3 class="font-bold">VENUE</h3>
              <%= image_tag "google-star-24px.svg", alt: "Rating star", class: "md:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-30px.svg", alt: "Rating star", class: "hidden md:block lg:hidden ml-2 mr-5" %>
              <%= image_tag "google-star-36px.svg", alt: "Rating star", class: "hidden lg:block ml-2 mr-5" %>
              <h3><%= @venue.venue_rating_average %></h3>
            </li>
            <li class="flex justify-end items-center w-48 pt-2 md:pt-2 lg:pt-4 [@media(max-height:700px)]:pt-1">
              <h3 class="font-bold mr-6">PRICE</h3>
              <h3>$<%= number_with_precision @venue.price_average.round(1), :precision => 2 %></h3>
            </li>
          </ul>
        </div>
        <div class="hidden" data-venue-details-target="detailsDiv">
          <div class="flex flex-col h-full text-saffron-mango-900 py-2 lg:mt-16 sm:text-2xl lg:text-2xl">
            <p class="text-right"><%= @venue.address %></p>
            <p class="text-right"><%= @venue.phone %></p>
            <%= link_to "Venue website", @venue.website, class: "transition ease-in-out duration-300 text-saffron-mango-800 hover:text-saffron-mango-950 text-right underline" %>
            <h4 class="mt-3 text-right">Venue opening hours</h4>
            <% if @venue.hours %>
              <% JSON.parse(@venue.hours).each do |hours| %>
                <p class="text-right"><%= hours %></p>
              <% end %>
            <% else %>
              <p class="text-right">Not provided</p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="mt-auto">
        <div data-venue-details-target="totalsDiv">
          <div class="flex justify-between items-center text-xl md:text-3xl border-y border-saffron-mango-950 px-4 py-1.5 md:py-2 lg:py-3 [@media(max-height:700px)]:py-1 my-2 md:my-3 lg:my-4 [@media(max-height:760px)]:my-1">
            <div class="flex justify-between items-center">
              <p>
                <h3 class="font-bold">TOTAL RATING</h3>
                <%= image_tag "google-star-24px.svg", alt: "Rating star", class: "md:hidden ml-2 mr-2" %>
                <%= image_tag "google-star-30px.svg", alt: "Rating star", class: "hidden md:block lg:hidden ml-2 mr-2" %>
                <%= image_tag "google-star-36px.svg", alt: "Rating star", class: "hidden lg:block ml-2 mr-2" %>
                <h3><%= @venue.total_rating_average %></h3>
              </p>
            </div>
            <div>
              <h3>Rated <%= @venue.ratings.count %> times</h3>
            </div>
          </div>
        </div>
        <div data-venue-details-target="formButton">
          <div class="flex justify-end pt-1 pb-3 sm:pb-5 lg:pb-6">
            <%= link_to "Rate venue's Parma", new_venue_rating_path(@venue), class: "transition ease-in-out duration-300 bg-transparent hover:bg-saffron-mango-600 text-saffron-mango-700 text-base md:text-xl font-semibold hover:text-white py-1 md:py-2 px-1.5 md:px-3 mr-2 border border-saffron-mango-600 hover:border-transparent rounded" %>
          </div>
        </div>
      </div>
    </div>
    <div class="w-full lg:w-2/3 h-full flex flex-col relative shadow-[0px_0px_10px_rgba(0,0,0,0.1)]"
      data-controller="google-maps"
      data-venue-details-target="mapDiv"
      data-google-maps-page-value="venue"
      data-google-maps-lat-value="<%= @venue.latitude %>"
      data-google-maps-lng-value="<%= @venue.longitude %>"
      data-google-maps-initial-load-value="true"
      data-google-maps-marker-clicked-value="false">
      <%= render "shared/map" %>
    </div>
  </turbo-frame>
</div>